Trình tự thực hiện: Load data -> Lọc -> Tách ID -> Xóa file info gốc

## Load data

## Import Libraries

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from PIL import Image
import os

## Read data

In [ ]:
# sắp xếp tên thư mục giống trên window
import re
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(data, key=alphanum_key)

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/raw_data/dendo"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
print(sort_listdir)
data_hanam = []
data_thainguyen = []
for i in sort_listdir:
    with open(path+"/"+i+"/info.txt", 'rb') as f:
      clean_lines = (line.replace(b',,',b',') for line in f)
      content = np.genfromtxt(clean_lines, delimiter=',')
      if i[:5] == "hanam":
            data_hanam.append(content)
      elif i[:10] == "thainguyen":
            data_thainguyen.append(content)
print("Ha Nam")
data_hanam[0]

['hanam_14.0.avi_save', 'hanam_20.0.avi_save', 'hanam_23.0.avi_save', 'hanam_26.0.avi_save', 'hanam_46.0.avi_save', 'hanam_52.0.avi_save', 'hanam_55.0.avi_save', 'hanam_72.0.avi_save', 'hanam_75.0.avi_save', 'hanam_81.0.avi_save', 'hanam_101.0.avi_save', 'thainguyen_0.0.avi_save', 'thainguyen_3.0.avi_save', 'thainguyen_4.0.avi_save', 'thainguyen_7.0.avi_save', 'thainguyen_8.0.avi_save', 'thainguyen_11.0.avi_save', 'thainguyen_12.0.avi_save', 'thainguyen_14.0.avi_save', 'thainguyen_15.0.avi_save', 'thainguyen_18.0.avi_save', 'thainguyen_19.0.avi_save', 'thainguyen_22.0.avi_save', 'thainguyen_23.0.avi_save', 'thainguyen_25.0.avi_save', 'thainguyen_26.0.avi_save', 'thainguyen_30.0.avi_save', 'thainguyen_33.0.avi_save', 'thainguyen_34.0.avi_save', 'thainguyen_36.0.avi_save', 'thainguyen_37.0.avi_save', 'thainguyen_40.0.avi_save', 'thainguyen_41.0.avi_save', 'thainguyen_44.0.avi_save', 'thainguyen_45.0.avi_save', 'thainguyen_51.0.avi_save', 'thainguyen_52.0.avi_save', 'thainguyen_55.0.avi_s

array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.06880e+03,
        1.30962e+02, 2.56731e+02],
       [2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 4.13289e+02,
        5.13116e+02, 9.35416e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 5.01311e+02,
        7.62312e+02, 1.25707e+03],
       ...,
       [1.48000e+02, 2.90000e+01, 3.00000e+00, ..., 1.22356e+03,
        7.20433e+01, 1.63053e+02],
       [1.48000e+02, 3.20000e+01, 0.00000e+00, ..., 2.37531e+03,
        1.61456e+03, 1.92000e+03],
       [1.48000e+02, 4.10000e+01, 0.00000e+00, ..., 1.07538e+03,
        7.86779e+01, 1.61755e+02]])

In [ ]:
len(data_hanam)

11

In [ ]:
len(data_thainguyen)

33

In [ ]:
#Read data VT (đèn xanh)
path = "/content/drive/MyDrive/Project/dataset/raw_data/denxanh"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
print(sort_listdir)
data_vungtau = []
for i in sort_listdir:
    with open(path+"/"+i+"/info.txt", 'rb') as f:
      clean_lines = (line.replace(b',,',b',') for line in f)
      content = np.genfromtxt(clean_lines, delimiter=',')
      data_vungtau.append(content)
print("Vung Tau")
data_vungtau[0]

['vungtau_1.0.avi_save', 'vungtau_12.0.avi_save', 'vungtau_100.0.avi_save', 'vungtau_101.0.avi_save', 'vungtau_106.0.avi_save', 'vungtau_107.0.avi_save', 'vungtau_112.0.avi_save', 'vungtau_123.0.avi_save', 'vungtau_124.0.avi_save', 'vungtau_129.0.avi_save', 'vungtau_130.0.avi_save', 'vungtau_135.0.avi_save']
Vung Tau


array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 2.00582e+03,
        5.96394e+01, 1.78341e+02],
       [2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 1.25303e+03,
        2.66466e+01, 1.46142e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 3.91611e+02,
        2.07548e+02, 3.80048e+02],
       ...,
       [1.48000e+02, 8.80000e+01, 0.00000e+00, ..., 4.17560e+02,
        6.75406e+02, 1.03181e+03],
       [1.48000e+02, 8.90000e+01, 0.00000e+00, ..., 1.70376e+03,
        5.91922e+02, 9.13236e+02],
       [1.48000e+02, 9.20000e+01, 0.00000e+00, ..., 1.66431e+03,
        8.86678e+02, 1.34604e+03]])

In [ ]:
len(data_vungtau)

12

## Tách sequence theo id và gán label

In [ ]:
#Xóa các data cũ
%cd /content/drive/MyDrive/Project/dataset/dendo/

path = '/content/drive/MyDrive/Project/dataset/denxanh/'
os.chdir(path)
os.listdir()
for i in os.listdir():
  path = path + i
  os.chdir(path)
  os.listdir()
  !rm info.txt
  path = '/content/drive/MyDrive/Project/dataset/denxanh/'

/content/drive/MyDrive/Project/dataset/dendo


###Đọc data đã lọc

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/filtered_dendo_data/hanam"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
data_hanam_loc = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i, delimiter=',')
        data_hanam_loc.append(content)
    except:
        print("Error")
print("Ha Nam")
data_hanam_loc[0]

Ha Nam


array([[2.00000e+00, 6.00000e+00, 3.00000e+00, ..., 1.17375e+03,
        9.23574e+02, 1.92000e+03],
       [3.00000e+00, 3.00000e+00, 0.00000e+00, ..., 4.54037e+02,
        8.19412e+02, 1.35594e+03],
       [3.00000e+00, 6.00000e+00, 3.00000e+00, ..., 1.16875e+03,
        9.23396e+02, 1.92000e+03],
       ...,
       [1.48000e+02, 6.00000e+00, 3.00000e+00, ..., 1.17000e+03,
        9.24380e+02, 1.92000e+03],
       [1.48000e+02, 2.60000e+01, 0.00000e+00, ..., 1.48974e+03,
        1.02148e+03, 1.62075e+03],
       [1.48000e+02, 3.20000e+01, 0.00000e+00, ..., 2.37531e+03,
        1.61456e+03, 1.92000e+03]])

In [ ]:
len(data_hanam_loc)

11

In [ ]:
#Doc data goc
path = "/content/drive/MyDrive/Project/dataset/dendo"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
print(sort_listdir)
data_hanam = []
data_thainguyen = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i+"/info.txt", delimiter=',')
        if i[:5] == "hanam":
            data_hanam.append(content)
        elif i[:10] == "thainguyen":
            data_thainguyen.append(content)
    except:
        print("Error")
print("Ha Nam")
data_hanam[0]

['hanam_14.0.avi_save', 'hanam_20.0.avi_save', 'hanam_23.0.avi_save', 'hanam_26.0.avi_save', 'hanam_46.0.avi_save', 'hanam_52.0.avi_save', 'hanam_55.0.avi_save', 'hanam_72.0.avi_save', 'hanam_75.0.avi_save', 'hanam_81.0.avi_save', 'hanam_101.0.avi_save', 'thainguyen_0.0.avi_save', 'thainguyen_3.0.avi_save', 'thainguyen_4.0.avi_save', 'thainguyen_7.0.avi_save', 'thainguyen_8.0.avi_save', 'thainguyen_11.0.avi_save', 'thainguyen_12.0.avi_save', 'thainguyen_14.0.avi_save', 'thainguyen_15.0.avi_save', 'thainguyen_18.0.avi_save', 'thainguyen_19.0.avi_save', 'thainguyen_22.0.avi_save', 'thainguyen_23.0.avi_save', 'thainguyen_25.0.avi_save', 'thainguyen_26.0.avi_save', 'thainguyen_30.0.avi_save', 'thainguyen_33.0.avi_save', 'thainguyen_34.0.avi_save', 'thainguyen_36.0.avi_save', 'thainguyen_37.0.avi_save', 'thainguyen_40.0.avi_save', 'thainguyen_41.0.avi_save', 'thainguyen_44.0.avi_save', 'thainguyen_45.0.avi_save', 'thainguyen_51.0.avi_save', 'thainguyen_52.0.avi_save', 'thainguyen_55.0.avi_s

array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.06880e+03,
        1.30962e+02, 2.56731e+02],
       [2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 4.13289e+02,
        5.13116e+02, 9.35416e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 5.01311e+02,
        7.62312e+02, 1.25707e+03],
       ...,
       [1.48000e+02, 2.90000e+01, 3.00000e+00, ..., 1.22356e+03,
        7.20433e+01, 1.63053e+02],
       [1.48000e+02, 3.20000e+01, 0.00000e+00, ..., 2.37531e+03,
        1.61456e+03, 1.92000e+03],
       [1.48000e+02, 4.10000e+01, 0.00000e+00, ..., 1.07538e+03,
        7.86779e+01, 1.61755e+02]])

In [ ]:
data_hanam[0]

array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.06880e+03,
        1.30962e+02, 2.56731e+02],
       [2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 4.13289e+02,
        5.13116e+02, 9.35416e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 5.01311e+02,
        7.62312e+02, 1.25707e+03],
       ...,
       [1.48000e+02, 2.90000e+01, 3.00000e+00, ..., 1.22356e+03,
        7.20433e+01, 1.63053e+02],
       [1.48000e+02, 3.20000e+01, 0.00000e+00, ..., 2.37531e+03,
        1.61456e+03, 1.92000e+03],
       [1.48000e+02, 4.10000e+01, 0.00000e+00, ..., 1.07538e+03,
        7.86779e+01, 1.61755e+02]])

In [ ]:
#hàm ghi file
def ghifile(path, content):
  with open(path+'id'+str(content[0][1])+'.txt', 'w') as f:
    for arr in content:
      arr = arr.tolist()  # conver to Python list
      f.write(','.join(map(str, arr)) + '\n')
  f.close()
    #fo = open(path+'id'+str(content[0][0])+'.txt', 'w')
    #for data in content:
        #fo.write(str(data) + "\n")
        # print(data)
    #fo.close()'''

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/dendo"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
sort_listdir

['hanam_14.0.avi_save',
 'hanam_20.0.avi_save',
 'hanam_23.0.avi_save',
 'hanam_26.0.avi_save',
 'hanam_46.0.avi_save',
 'hanam_52.0.avi_save',
 'hanam_55.0.avi_save',
 'hanam_72.0.avi_save',
 'hanam_75.0.avi_save',
 'hanam_81.0.avi_save',
 'hanam_101.0.avi_save',
 'thainguyen_0.0.avi_save',
 'thainguyen_3.0.avi_save',
 'thainguyen_4.0.avi_save',
 'thainguyen_7.0.avi_save',
 'thainguyen_8.0.avi_save',
 'thainguyen_11.0.avi_save',
 'thainguyen_12.0.avi_save',
 'thainguyen_14.0.avi_save',
 'thainguyen_15.0.avi_save',
 'thainguyen_18.0.avi_save',
 'thainguyen_19.0.avi_save',
 'thainguyen_22.0.avi_save',
 'thainguyen_23.0.avi_save',
 'thainguyen_25.0.avi_save',
 'thainguyen_26.0.avi_save',
 'thainguyen_30.0.avi_save',
 'thainguyen_33.0.avi_save',
 'thainguyen_34.0.avi_save',
 'thainguyen_36.0.avi_save',
 'thainguyen_37.0.avi_save',
 'thainguyen_40.0.avi_save',
 'thainguyen_41.0.avi_save',
 'thainguyen_44.0.avi_save',
 'thainguyen_45.0.avi_save',
 'thainguyen_51.0.avi_save',
 'thainguyen_52

Tách cho Hà Nam

In [ ]:
id = []
sequence_id = []
labels = []
for i in data_hanam_loc: #i la bo du lieu folder thu i
    for j in i:
      id.append(j[1])
    break
print(list(set(id)))


number_folder = 0
for i in data_hanam_loc: #i la bo du lieu folder thu i
    #lấy ra tập chứa các id trong folder
    for j in i:
      id.append(j[1])
    for l in id: #duyet id tu tap id
      for k in data_hanam[number_folder]: #duyet qua cac frame cua data goc tuong ung
        if k[1]==l: #neu id frame = id trong tap id
          sequence_id.append(k[:]) #lay ra thong tin sequence  
      #print(sequence_id)
      #ghi ra file sequence of id
      path = '/content/drive/MyDrive/Project/dataset/dendo/' + sort_listdir[number_folder] + '/'
      ghifile(path, sequence_id)
      sequence_id = [] #khoi tao lai sequence_id = rong
    number_folder = number_folder + 1
    id = [] #khởi tạo lại id = rỗng


[32.0, 33.0, 3.0, 36.0, 6.0, 9.0, 12.0, 45.0, 17.0, 25.0, 26.0, 28.0]


Tách cho Thái Nguyên không vượt đèn

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/filtered_dendo_data/thainguyen"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
data_thainguyen_loc = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i, delimiter=',')
        data_thainguyen_loc.append(content)
    except:
        print("Error")
print("Thai Nguyen")
data_thainguyen_loc[31]

Thai Nguyen


array([[2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 1.11902e+03,
        8.16898e+02, 1.27207e+03],
       [2.00000e+00, 4.00000e+00, 0.00000e+00, ..., 1.71827e+03,
        0.00000e+00, 1.71058e+02],
       [2.00000e+00, 5.00000e+00, 3.00000e+00, ..., 2.21231e+03,
        0.00000e+00, 1.64639e+02],
       ...,
       [1.48000e+02, 3.30000e+01, 0.00000e+00, ..., 5.73011e+02,
        9.40124e+02, 1.40050e+03],
       [1.48000e+02, 7.30000e+01, 1.00000e+00, ..., 1.67152e+03,
        4.02896e+00, 3.15162e+02],
       [1.48000e+02, 7.80000e+01, 3.00000e+00, ..., 2.11089e+03,
        7.27787e-01, 1.77121e+02]])

In [ ]:
data_thainguyen[31]

array([[2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 1.11902e+03,
        8.16898e+02, 1.27207e+03],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 2.41903e+03,
        4.93934e+02, 8.25853e+02],
       [2.00000e+00, 4.00000e+00, 0.00000e+00, ..., 1.71827e+03,
        0.00000e+00, 1.71058e+02],
       ...,
       [1.48000e+02, 7.30000e+01, 1.00000e+00, ..., 1.67152e+03,
        4.02896e+00, 3.15162e+02],
       [1.48000e+02, 7.80000e+01, 3.00000e+00, ..., 2.11089e+03,
        7.27787e-01, 1.77121e+02],
       [1.48000e+02, 8.40000e+01, 0.00000e+00, ..., 2.24304e+03,
        5.93164e+02, 9.59021e+02]])

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/dendo"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
sort_listdir[11+32]

'thainguyen_67.0.avi_save'

In [ ]:
id = []
sequence_id = []
labels = []
for i in data_thainguyen_loc: #i la bo du lieu folder thu i
    for j in i:
      id.append(j[1])
    break
print(list(set(id)))

number_folder = 11
number_data_tn = 0
for i in data_thainguyen_loc: #i la bo du lieu folder thu i
    #lấy ra tập chứa các id trong folder
    for j in i:
      id.append(j[1])
    for l in id: #duyet id tu tap id
      for k in data_thainguyen[number_data_tn]: #duyet qua cac frame
        if k[1]==l: #neu id frame = id trong tap id
          sequence_id.append(k[:]) #lay ra thong tin sequence  
      #print(sequence_id)
      #ghi ra file sequence of id
      path = '/content/drive/MyDrive/Project/dataset/dendo/' + sort_listdir[number_folder] + '/'
      ghifile(path, sequence_id)
      sequence_id = [] #khoi tao lai sequence_id = rong
    number_folder = number_folder + 1
    number_data_tn = number_data_tn + 1
    id = [] #khởi tạo lại id = rỗng

[1.0, 4.0, 5.0, 7.0, 8.0, 9.0, 13.0, 16.0, 17.0, 19.0, 25.0, 27.0, 28.0, 33.0, 34.0, 41.0, 42.0, 46.0, 47.0, 49.0, 50.0, 53.0, 54.0, 64.0, 66.0, 68.0, 69.0, 73.0, 77.0, 82.0, 87.0, 97.0, 110.0]


Tách cho Thái Nguyên vượt đèn

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/filtered_denxanh_data/thainguyen"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
data_thainguyen_loc = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i, delimiter=',')
        data_thainguyen_loc.append(content)
    except:
        print("Error")
print("Thai Nguyen")
data_thainguyen_loc[31]

Thai Nguyen


array([[2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 2.41903e+03,
        4.93934e+02, 8.25853e+02],
       [3.00000e+00, 3.00000e+00, 0.00000e+00, ..., 2.43776e+03,
        4.71893e+02, 7.95807e+02],
       [4.00000e+00, 3.00000e+00, 0.00000e+00, ..., 2.45443e+03,
        4.52043e+02, 7.69614e+02],
       ...,
       [1.46000e+02, 8.40000e+01, 0.00000e+00, ..., 2.21691e+03,
        6.67753e+02, 1.05766e+03],
       [1.47000e+02, 8.40000e+01, 0.00000e+00, ..., 2.22665e+03,
        6.34710e+02, 1.00291e+03],
       [1.48000e+02, 8.40000e+01, 0.00000e+00, ..., 2.24304e+03,
        5.93164e+02, 9.59021e+02]])

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/denxanh"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
sort_listdir

['thainguyen_0.0.avi_save',
 'thainguyen_3.0.avi_save',
 'thainguyen_4.0.avi_save',
 'thainguyen_7.0.avi_save',
 'thainguyen_8.0.avi_save',
 'thainguyen_11.0.avi_save',
 'thainguyen_12.0.avi_save',
 'thainguyen_14.0.avi_save',
 'thainguyen_15.0.avi_save',
 'thainguyen_18.0.avi_save',
 'thainguyen_19.0.avi_save',
 'thainguyen_22.0.avi_save',
 'thainguyen_23.0.avi_save',
 'thainguyen_25.0.avi_save',
 'thainguyen_26.0.avi_save',
 'thainguyen_30.0.avi_save',
 'thainguyen_33.0.avi_save',
 'thainguyen_34.0.avi_save',
 'thainguyen_36.0.avi_save',
 'thainguyen_37.0.avi_save',
 'thainguyen_40.0.avi_save',
 'thainguyen_41.0.avi_save',
 'thainguyen_44.0.avi_save',
 'thainguyen_45.0.avi_save',
 'thainguyen_51.0.avi_save',
 'thainguyen_52.0.avi_save',
 'thainguyen_55.0.avi_save',
 'thainguyen_56.0.avi_save',
 'thainguyen_59.0.avi_save',
 'thainguyen_62.0.avi_save',
 'thainguyen_63.0.avi_save',
 'thainguyen_66.0.avi_save',
 'thainguyen_67.0.avi_save',
 'vungtau_1.0.avi_save',
 'vungtau_12.0.avi_save

In [ ]:
id = []
sequence_id = []
labels = []
for i in data_thainguyen_loc: #i la bo du lieu folder thu i
    for j in i:
      id.append(j[1])
    break
print(list(set(id)))

number_folder = 0
for i in data_thainguyen_loc: #i la bo du lieu folder thu i
    #lấy ra tập chứa các id trong folder
    for j in i:
      id.append(j[1])
    for l in id: #duyet id tu tap id
      for k in data_thainguyen[number_folder]: #duyet qua cac frame
        if k[1]==l: #neu id frame = id trong tap id
          sequence_id.append(k[:]) #lay ra thong tin sequence  
      #print(sequence_id)
      #ghi ra file sequence of id
      path = '/content/drive/MyDrive/Project/dataset/denxanh/' + sort_listdir[number_folder] + '/'
      ghifile(path, sequence_id)
      sequence_id = [] #khoi tao lai sequence_id = rong
    number_folder = number_folder + 1
    id = [] #khởi tạo lại id = rỗng

[2.0, 3.0, 6.0, 8.0, 11.0, 16.0, 17.0, 23.0, 30.0, 32.0, 34.0, 37.0, 42.0, 44.0, 47.0, 56.0, 57.0, 67.0, 73.0, 78.0, 84.0]


Tách cho Vũng Tàu

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/filtered_denxanh_data/vungtau"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
data_vungtau_loc = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i, delimiter=',')
        data_vungtau_loc.append(content)
    except:
        print("Error")
print("Vung Tau")
data_vungtau_loc[0]

Vung Tau


array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 2.00582e+03,
        5.96394e+01, 1.78341e+02],
       [2.00000e+00, 4.00000e+00, 0.00000e+00, ..., 1.94264e+03,
        2.04231e+02, 3.69808e+02],
       [2.00000e+00, 5.00000e+00, 0.00000e+00, ..., 2.06310e+03,
        1.76683e+02, 3.31010e+02],
       ...,
       [1.48000e+02, 7.20000e+01, 0.00000e+00, ..., 6.87558e+02,
        5.87898e+02, 9.14392e+02],
       [1.48000e+02, 8.90000e+01, 0.00000e+00, ..., 1.70376e+03,
        5.91922e+02, 9.13236e+02],
       [1.48000e+02, 9.20000e+01, 0.00000e+00, ..., 1.66431e+03,
        8.86678e+02, 1.34604e+03]])

In [ ]:
#doc data goc
path = "/content/drive/MyDrive/Project/dataset/raw_data/denxanh"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
data_vungtau = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i+"/info.txt", delimiter=',')
        data_vungtau.append(content)
    except:
        print("Error")
print("Vung Tau")
data_vungtau[0]

Vung Tau


array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 2.00582e+03,
        5.96394e+01, 1.78341e+02],
       [2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 1.25303e+03,
        2.66466e+01, 1.46142e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 3.91611e+02,
        2.07548e+02, 3.80048e+02],
       ...,
       [1.48000e+02, 8.80000e+01, 0.00000e+00, ..., 4.17560e+02,
        6.75406e+02, 1.03181e+03],
       [1.48000e+02, 8.90000e+01, 0.00000e+00, ..., 1.70376e+03,
        5.91922e+02, 9.13236e+02],
       [1.48000e+02, 9.20000e+01, 0.00000e+00, ..., 1.66431e+03,
        8.86678e+02, 1.34604e+03]])

In [ ]:
path = "/content/drive/MyDrive/Project/dataset/denxanh"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
sort_listdir[33]

'vungtau_1.0.avi_save'

In [ ]:
id = []
sequence_id = []
labels = []
for i in data_vungtau_loc: #i la bo du lieu folder thu i
    for j in i:
      id.append(j[1])
    break
print(list(set(id)))

number_folder = 33
number_data_vt = 0
for i in data_vungtau_loc: #i la bo du lieu folder thu i
    #lấy ra tập chứa các id trong folder
    for j in i:
      id.append(j[1])
    for l in id: #duyet id tu tap id
      for k in data_vungtau[number_data_vt]: #duyet qua cac frame
        if k[1]==l: #neu id frame = id trong tap id
          sequence_id.append(k[:]) #lay ra thong tin sequence  
      #print(sequence_id)
      #ghi ra file sequence of id
      path = '/content/drive/MyDrive/Project/dataset/denxanh/' + sort_listdir[number_folder] + '/'
      ghifile(path, sequence_id)
      sequence_id = [] #khoi tao lai sequence_id = rong
    number_folder = number_folder + 1
    number_data_vt = number_data_vt + 1
    id = [] #khởi tạo lại id = rỗng

[1.0, 4.0, 5.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 19.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 37.0, 39.0, 40.0, 42.0, 43.0, 47.0, 51.0, 53.0, 54.0, 59.0, 60.0, 61.0, 62.0, 65.0, 67.0, 69.0, 71.0, 72.0, 78.0, 89.0, 92.0]


In [ ]:
print(len(data_hanam))
print(len(data_thainguyen))
print(len(data_vungtau))

11
33
12


## Lọc data

In [ ]:
def linear_equation(x1,y1,x2,y2):
    a = (y1-y2)/(x1-x2)
    c = y1-a*x1
    b = -1
    return a, b, c

In [ ]:
def safe(value1, value2):
    if value1*value2>=0:
        return True
    return False

Lọc data ở Hà Nam

In [ ]:
# Các điểm cho trước trên vùng lọc
x1 = 2.9411764705882035
y1 = 1142.8823529411764
x2 = 935.2941176470588
y2 = 701.7058823529411
x3 = 1752.941176470588
y3 = 725.235294117647
x4 = 2400.0
y4 = 1916.4117647058822
# Điểm để xét trong vùng đang quan sát
X = 1280
Y = 1920

# Đường thẳng lọc data hà nam
a1, b1, c1 = linear_equation(x1,y1,x2,y2)
a2, b2, c2 = linear_equation(x2,y2,x3,y3)
a3, b3, c3 = linear_equation(x3,y3,x4,y4)

In [ ]:
filtered_data_hanam = []

for datas in data_hanam:
    filters = []
    for data in datas:
        if (safe(a1*X+b1*Y+c1, a1*((data[4]+data[3])/2)+b1*((data[6]+data[5])/2)+c1)==True 
        and safe(a2*X+b2*Y+c2, a2*((data[4]+data[3])/2)+b2*((data[6]+data[5])/2)+c2)==True
        and safe(a3*X+b3*Y+c3, a3*((data[4]+data[3])/2)+b3*((data[6]+data[5])/2)+c3)==True):
            filters.append(data)
    filtered_data_hanam.append(filters)

In [ ]:
len(filtered_data_hanam[0])

497

In [ ]:
len(data_hanam[0])

1402

Lọc data Thái Nguyên

In [ ]:
#lọc không vượt đèn đỏ
# Các điểm cho trước trên vùng lọc
x5 = 3.0
y5 = 1436.0
x6 = 645.0
y6 = 760.0
x7 = 1369.0
y7 = 762.0
x8 = 1096
y8 = 1919
# Điểm để xét trong vùng đang quan sát
X1 = 849.0
Y1 = 1070.0

# Đường thẳng lọc data thái nguyên không vượt đèn đỏ
a4, b4, c4 = linear_equation(x5,y5,x6,y6)
a5, b5, c5 = linear_equation(x6,y6,x7,y7)
a6, b6, c6 = linear_equation(x7,y7,x8,y8)

#lọc vượt đèn đỏ
#các điểm cho trước trên vùng lọc
x9 = 1277.0
y9 = 1918.0
x10 = 1469.0
y10 = 802.0
x11 = 1717.0
y11 = 386.0
x12 = 2559
y12 = 104
# Điểm để xét trong vùng đang quan sát
X = 1717.0
Y = 802.0

# Đường thẳng lọc data thái nguyên vượt đèn đỏ
a7, b7, c7 = linear_equation(x9,y9,x10,y10)
a8, b8, c8 = linear_equation(x10,y10,x11,y11)
a9, b9, c9 = linear_equation(x11,y11,x12,y12)

In [ ]:
filtered_data_thainguyen_kovuot = []
filtered_data_thainguyen_vuot = []
for datas in data_thainguyen:
    filters_kovuot = []
    filters_vuot = []
    for data in datas:
        if (safe(a4*X1+b4*Y1+c4, a4*((data[4]+data[3])/2)+b4*((data[6]+data[5])/2)+c4)==True 
        and safe(a5*X1+b5*Y1+c5, a5*((data[4]+data[3])/2)+b5*((data[6]+data[5])/2)+c5)==True
        and safe(a6*X1+b6*Y1+c6, a6*((data[4]+data[3])/2)+b6*((data[6]+data[5])/2)+c6)==True):
            filters_kovuot.append(data)
        if (safe(a7*X+b7*Y+c7, a7*((data[4]+data[3])/2)+b7*((data[6]+data[5])/2)+c7)==True 
        and safe(a8*X+b8*Y+c8, a8*((data[4]+data[3])/2)+b8*((data[6]+data[5])/2)+c8)==True
        and safe(a9*X+b9*Y+c9, a9*((data[4]+data[3])/2)+b9*((data[6]+data[5])/2)+c9)==True):
            filters_vuot.append(data)
    filtered_data_thainguyen_kovuot.append(filters_kovuot)
    filtered_data_thainguyen_vuot.append(filters_vuot)

In [ ]:
len(data_thainguyen[0])

1871

In [ ]:
len(filtered_data_thainguyen_kovuot[4])

686

In [ ]:
len(filtered_data_thainguyen_vuot[4])

214

Lọc data Vũng Tàu (đèn xanh)

In [ ]:
# Các điểm cho trước trên vùng lọc
x8 = 0.0
y8 = 1130.0
x9 = 807.0
y9 = 606.0
x10 = 2361
y10 = 658
# Điểm để xét trong vùng đang quan sát
X = 807.0
Y = 1130.0

# Đường thẳng lọc data vũng tàu
a6, b6, c6 = linear_equation(x8,y8,x9,y9)
a7, b7, c7 = linear_equation(x9,y9,x10,y10)

In [ ]:
filtered_data_vungtau = []

for datas in data_vungtau:
    filters = []
    for data in datas:
        if (safe(a6*X+b6*Y+c6, a6*((data[4]+data[3])/2)+b6*((data[6]+data[5])/2)+c6)==True 
        and safe(a7*X+b7*Y+c7, a7*((data[4]+data[3])/2)+b7*((data[6]+data[5])/2)+c7)==True):
            filters.append(data)
    filtered_data_vungtau.append(filters)

In [ ]:
len(data_vungtau[0])

3529

In [ ]:
len(filtered_data_vungtau[0])

2242

## Ghi kết quả lọc được ra file

Ghi dữ liệu của Hà Nam và Thái Nguyên

Ghi ra Hà Nam

In [ ]:
path = '/content/drive/MyDrive/Project/dataset/filtered_dendo_data/hanam/'

i=0
for datas in filtered_data_hanam:
  i = i + 1
  with open(path+str(i)+'.txt', 'w') as f:
    for data in datas:
      data = data.tolist()  # conver to Python list
      f.write(','.join(map(str, data)) + '\n')
  f.close()

Ghi ra Thái Nguyên

In [ ]:
#không vượt đèn đỏ
path = '/content/drive/MyDrive/Project/dataset/filtered_dendo_data/thainguyen/'

i=0
for datas in filtered_data_thainguyen_kovuot:
  i = i + 1
  with open(path+str(i)+'.txt', 'w') as f:
    for data in datas:
      data = data.tolist()  # conver to Python list
      f.write(','.join(map(str, data)) + '\n')
  f.close()

In [ ]:
#vượt đèn đỏ
path = '/content/drive/MyDrive/Project/dataset/filtered_denxanh_data/thainguyen/'

i=0
for datas in filtered_data_thainguyen_vuot:
  i = i + 1
  with open(path+str(i)+'.txt', 'w') as f:
    for data in datas:
      data = data.tolist()  # conver to Python list
      f.write(','.join(map(str, data)) + '\n')
  f.close()

Ghi dữ liệu Vũng Tàu

In [ ]:
path = '/content/drive/MyDrive/Project/dataset/filtered_denxanh_data/vungtau/'

i=0
for datas in filtered_data_vungtau:
  i = i + 1
  with open(path+str(i)+'.txt', 'w') as f:
    for data in datas:
      data = data.tolist()  # conver to Python list
      f.write(','.join(map(str, data)) + '\n')
  f.close()

dùng lọc để lấy id xét xong quay lại file gốc lấy sequence của các id xuất hiện trong file lọc 