Trình tự thực hiện: Load data -> Lọc -> Tách ID -> Xóa file info gốc

## Load data

## Import Libraries

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np
import pandas as pd
from PIL import Image
import os

## Read data

In [4]:
# sắp xếp tên thư mục giống trên window
import re
def sorted_alphanumeric(data):
    convert = lambda text: int(text) if text.isdigit() else text.lower()
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ] 
    return sorted(data, key=alphanum_key)

In [ ]:
#code xoa dong trong file txt
"""
path = "/content/drive/MyDrive/Project/data_test/denxanh/"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
print(sort_listdir)

#xóa line trắng file txt
for folder in sort_listdir[1:]:
  path = path + folder
  os.chdir(path)
  with open("info.txt","r") as f, open("info1.txt","w") as outfile:
    for i in f.readlines():
       if not i.strip():
           continue
       if i:
           outfile.write(i)    
  path = "/content/drive/MyDrive/Project/data_test/denxanh/"
"""

['hanam_1.0.avi_save', 'hanam_4.0.avi_save', 'hanam_30.0.avi_save', 'hanam_33.0.avi_save', 'hanam_59.0.avi_save', 'hanam_62.0.avi_save', 'hanam_88.0.avi_save', 'hanam_91.0.avi_save']


In [5]:
#Read data vung tau (den xanh)
path = "/content/drive/MyDrive/Project/data_test_new/denxanh"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
print(len(sort_listdir))
data_vungtau = []
for i in sort_listdir:
  with open(path+"/"+i+"/info.txt", 'rb') as f:
      clean_lines = (line.replace(b',,',b',') for line in f)
      content = np.genfromtxt(clean_lines, delimiter=',')
      data_vungtau.append(content)
print("Vung Tau")
data_vungtau[0]

14
Vung Tau


array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.93252e+03,
        9.49399e+01, 2.17752e+02],
       [2.00000e+00, 2.00000e+00, 0.00000e+00, ..., 3.89808e+02,
        1.71707e+02, 3.16947e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 2.05743e+03,
        1.60601e+02, 3.12764e+02],
       ...,
       [1.48000e+02, 6.50000e+01, 0.00000e+00, ..., 2.06690e+03,
        3.24519e-01, 8.16707e+01],
       [1.48000e+02, 7.00000e+01, 0.00000e+00, ..., 1.77654e+03,
        3.06202e+02, 5.24567e+02],
       [1.48000e+02, 7.90000e+01, 3.00000e+00, ..., 8.39975e+02,
        6.36022e+02, 1.01672e+03]])

In [ ]:
#Read data ha nam (đèn xanh)
path = "/content/drive/MyDrive/Project/data_test/denxanh"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
print(len(sort_listdir))
data_hanam = []
for i in sort_listdir:
  with open(path+"/"+i+"/info.txt", 'rb') as f:
      clean_lines = (line.replace(b',,',b',') for line in f)
      content = np.genfromtxt(clean_lines, delimiter=',')
      data_hanam.append(content)
print("Ha Nam")
data_hanam[0]

8
Ha Nam


array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.51727e+03,
        7.06722e+02, 1.10330e+03],
       [2.00000e+00, 2.00000e+00, 2.00000e+00, ..., 3.86647e+02,
        7.94281e+02, 1.30736e+03],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 2.19657e+02,
        5.36285e+02, 9.15557e+02],
       ...,
       [1.48000e+02, 2.70000e+01, 0.00000e+00, ..., 9.66610e+02,
        1.71094e+02, 2.89579e+02],
       [1.48000e+02, 2.80000e+01, 3.00000e+00, ..., 1.18173e+03,
        5.40555e+02, 9.00991e+02],
       [1.48000e+02, 2.90000e+01, 0.00000e+00, ..., 9.68149e+02,
        1.10084e+02, 2.05781e+02]])

## Tách sequence theo id và gán label

Xóa file info trong từng thư mục

In [13]:
#Xóa các data cũ

path = '/content/drive/MyDrive/Project/data_test_new/denxanh/'
os.chdir(path)
os.listdir()
for i in os.listdir():
  path = path + i
  os.chdir(path)
  os.listdir()
  !rm info.txt
  path = '/content/drive/MyDrive/Project/data_test_new/denxanh/'

###Đọc data đã lọc

In [ ]:
path = "/content/drive/MyDrive/Project/data_test_new/filtered_denxanh_data"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
data_hanam_loc = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i, delimiter=',')
        data_hanam_loc.append(content)
    except:
        print("Error")
print("Ha Nam")
data_hanam_loc[7]

Ha Nam


array([[2.00000e+00, 1.00000e+00, 3.00000e+00, ..., 1.13875e+03,
        1.09801e+03, 1.91037e+03],
       [2.00000e+00, 3.00000e+00, 3.00000e+00, ..., 1.31490e+03,
        3.04950e+02, 5.44900e+02],
       [2.00000e+00, 7.00000e+00, 0.00000e+00, ..., 1.54605e+03,
        6.62865e+02, 1.07448e+03],
       ...,
       [1.46000e+02, 1.60000e+01, 3.00000e+00, ..., 1.79683e+03,
        1.33341e+02, 2.47428e+02],
       [1.47000e+02, 8.00000e+00, 3.00000e+00, ..., 1.87293e+03,
        1.64820e+02, 2.86046e+02],
       [1.48000e+02, 8.00000e+00, 3.00000e+00, ..., 1.87361e+03,
        1.64423e+02, 2.86442e+02]])

In [ ]:
#Doc data goc
path = "/content/drive/MyDrive/Project/data_test/denxanh"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
print(sort_listdir)
data_hanam = []
data_thainguyen = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i+"/info.txt", delimiter=',')
        if i[:5] == "hanam":
            data_hanam.append(content)
        elif i[:10] == "thainguyen":
            data_thainguyen.append(content)
    except:
        print("Error")
print("Ha Nam")
data_hanam[0]

['hanam_14.0.avi_save', 'hanam_20.0.avi_save', 'hanam_23.0.avi_save', 'hanam_26.0.avi_save', 'hanam_46.0.avi_save', 'hanam_52.0.avi_save', 'hanam_55.0.avi_save', 'hanam_72.0.avi_save', 'hanam_75.0.avi_save', 'hanam_81.0.avi_save', 'hanam_101.0.avi_save', 'thainguyen_0.0.avi_save', 'thainguyen_3.0.avi_save', 'thainguyen_4.0.avi_save', 'thainguyen_7.0.avi_save', 'thainguyen_8.0.avi_save', 'thainguyen_11.0.avi_save', 'thainguyen_12.0.avi_save', 'thainguyen_14.0.avi_save', 'thainguyen_15.0.avi_save', 'thainguyen_18.0.avi_save', 'thainguyen_19.0.avi_save', 'thainguyen_22.0.avi_save', 'thainguyen_23.0.avi_save', 'thainguyen_25.0.avi_save', 'thainguyen_26.0.avi_save', 'thainguyen_30.0.avi_save', 'thainguyen_33.0.avi_save', 'thainguyen_34.0.avi_save', 'thainguyen_36.0.avi_save', 'thainguyen_37.0.avi_save', 'thainguyen_40.0.avi_save', 'thainguyen_41.0.avi_save', 'thainguyen_44.0.avi_save', 'thainguyen_45.0.avi_save', 'thainguyen_51.0.avi_save', 'thainguyen_52.0.avi_save', 'thainguyen_55.0.avi_s

array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.06880e+03,
        1.30962e+02, 2.56731e+02],
       [2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 4.13289e+02,
        5.13116e+02, 9.35416e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 5.01311e+02,
        7.62312e+02, 1.25707e+03],
       ...,
       [1.48000e+02, 2.90000e+01, 3.00000e+00, ..., 1.22356e+03,
        7.20433e+01, 1.63053e+02],
       [1.48000e+02, 3.20000e+01, 0.00000e+00, ..., 2.37531e+03,
        1.61456e+03, 1.92000e+03],
       [1.48000e+02, 4.10000e+01, 0.00000e+00, ..., 1.07538e+03,
        7.86779e+01, 1.61755e+02]])

In [ ]:
data_hanam[7]

array([[2.00000e+00, 1.00000e+00, 3.00000e+00, ..., 1.13875e+03,
        1.09801e+03, 1.91037e+03],
       [2.00000e+00, 2.00000e+00, 0.00000e+00, ..., 6.32265e+02,
        4.82879e+02, 8.12195e+02],
       [2.00000e+00, 3.00000e+00, 3.00000e+00, ..., 1.31490e+03,
        3.04950e+02, 5.44900e+02],
       ...,
       [1.48000e+02, 8.00000e+00, 3.00000e+00, ..., 1.87361e+03,
        1.64423e+02, 2.86442e+02],
       [1.48000e+02, 3.50000e+01, 0.00000e+00, ..., 2.65731e+02,
        6.06014e+02, 1.01046e+03],
       [1.48000e+02, 4.30000e+01, 0.00000e+00, ..., 9.71731e+02,
        1.26959e+02, 2.48329e+02]])

In [14]:
#hàm ghi file
def ghifile(path, content):
  with open(path+'id'+str(content[0][1])+'.txt', 'w') as f:
    for arr in content:
      arr = arr.tolist()  # conver to Python list
      f.write(','.join(map(str, arr)) + '\n')
  f.close()
    #fo = open(path+'id'+str(content[0][0])+'.txt', 'w')
    #for data in content:
        #fo.write(str(data) + "\n")
        # print(data)
    #fo.close()'''

In [15]:
path = "/content/drive/MyDrive/Project/data_test_new/denxanh"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
sort_listdir

['vungtau_17.0.avi_save',
 'vungtau_18.0.avi_save',
 'vungtau_147.0.avi_save',
 'vungtau_152.0.avi_save',
 'vungtau_157.0.avi_save',
 'vungtau_163.0.avi_save',
 'vungtau_169.0.avi_save',
 'vungtau_174.0.avi_save',
 'vungtau_175.0.avi_save',
 'vungtau_181.0.avi_save',
 'vungtau_185.0.avi_save',
 'vungtau_186.0.avi_save',
 'vungtau_191.0.avi_save',
 'vungtau_196.0.avi_save']

Tách cho Hà Nam

In [ ]:
id = []
sequence_id = []
labels = []
for i in data_hanam_loc: #i la bo du lieu folder thu i
    for j in i:
      id.append(j[1])
    break
print(list(set(id)))


number_folder = 0
for i in data_hanam_loc: #i la bo du lieu folder thu i
    #lấy ra tập chứa các id trong folder
    for j in i:
      id.append(j[1])
    for l in id: #duyet id tu tap id
      for k in data_hanam[number_folder]: #duyet qua cac frame cua data goc tuong ung
        if k[1]==l: #neu id frame = id trong tap id
          sequence_id.append(k[:]) #lay ra thong tin sequence  
      #print(sequence_id)
      #ghi ra file sequence of id
      path = '/content/drive/MyDrive/Project/data_test/denxanh/' + sort_listdir[number_folder] + '/'
      ghifile(path, sequence_id)
      sequence_id = [] #khoi tao lai sequence_id = rong
    number_folder = number_folder + 1
    id = [] #khởi tạo lại id = rỗng


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 9.0, 13.0, 15.0, 21.0, 22.0, 23.0, 25.0, 26.0, 28.0]


Tách cho Vũng Tàu

In [16]:
path = "/content/drive/MyDrive/Project/data_test_new/filtered_denxanh_data"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
data_vungtau_loc = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i, delimiter=',')
        data_vungtau_loc.append(content)
    except:
        print("Error")
print("Vung Tau")
data_vungtau_loc[0]

Vung Tau


array([[2.00000e+00, 8.00000e+00, 0.00000e+00, 9.83238e+02, 1.16925e+03,
        9.04059e+02, 1.34335e+03],
       [2.00000e+00, 9.00000e+00, 0.00000e+00, 1.41395e+03, 1.59018e+03,
        7.78965e+02, 1.19676e+03],
       [3.00000e+00, 8.00000e+00, 0.00000e+00, 1.01401e+03, 1.18756e+03,
        8.60527e+02, 1.28006e+03],
       [3.00000e+00, 9.00000e+00, 0.00000e+00, 1.42427e+03, 1.60124e+03,
        7.51166e+02, 1.15675e+03],
       [3.00000e+00, 2.50000e+01, 3.00000e+00, 0.00000e+00, 1.92369e+02,
        1.05855e+03, 1.91978e+03],
       [4.00000e+00, 8.00000e+00, 0.00000e+00, 1.04364e+03, 1.21656e+03,
        7.97035e+02, 1.20124e+03],
       [4.00000e+00, 9.00000e+00, 0.00000e+00, 1.43612e+03, 1.60827e+03,
        7.16648e+02, 1.10887e+03],
       [4.00000e+00, 2.50000e+01, 3.00000e+00, 8.98752e-01, 2.64441e+02,
        9.84997e+02, 1.86794e+03],
       [5.00000e+00, 8.00000e+00, 0.00000e+00, 1.07072e+03, 1.22989e+03,
        7.61051e+02, 1.14962e+03],
       [5.00000e+00, 9.00000

In [ ]:
#doc data goc
path = "/content/drive/MyDrive/Project/data_test/raw_data/dendo"
os.chdir(path)
sort_listdir = sorted_alphanumeric(os.listdir())
data_vungtau = []
for i in sort_listdir:
    # content = np.loadtxt(path+"/"+i+"/info.txt", delimiter=',')
    # content = pd.read_csv(path+"/"+i+"/info.txt")
    try:
        content = np.genfromtxt(path+"/"+i+"/info.txt", delimiter=',')
        data_vungtau.append(content)
    except:
        print("Error")
print("Vung Tau")
data_vungtau[0]

Vung Tau


array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 2.00582e+03,
        5.96394e+01, 1.78341e+02],
       [2.00000e+00, 2.00000e+00, 3.00000e+00, ..., 1.25303e+03,
        2.66466e+01, 1.46142e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 3.91611e+02,
        2.07548e+02, 3.80048e+02],
       ...,
       [1.48000e+02, 8.80000e+01, 0.00000e+00, ..., 4.17560e+02,
        6.75406e+02, 1.03181e+03],
       [1.48000e+02, 8.90000e+01, 0.00000e+00, ..., 1.70376e+03,
        5.91922e+02, 9.13236e+02],
       [1.48000e+02, 9.20000e+01, 0.00000e+00, ..., 1.66431e+03,
        8.86678e+02, 1.34604e+03]])

In [17]:
data_vungtau[0]

array([[2.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.93252e+03,
        9.49399e+01, 2.17752e+02],
       [2.00000e+00, 2.00000e+00, 0.00000e+00, ..., 3.89808e+02,
        1.71707e+02, 3.16947e+02],
       [2.00000e+00, 3.00000e+00, 0.00000e+00, ..., 2.05743e+03,
        1.60601e+02, 3.12764e+02],
       ...,
       [1.48000e+02, 6.50000e+01, 0.00000e+00, ..., 2.06690e+03,
        3.24519e-01, 8.16707e+01],
       [1.48000e+02, 7.00000e+01, 0.00000e+00, ..., 1.77654e+03,
        3.06202e+02, 5.24567e+02],
       [1.48000e+02, 7.90000e+01, 3.00000e+00, ..., 8.39975e+02,
        6.36022e+02, 1.01672e+03]])

In [18]:
path = "/content/drive/MyDrive/Project/data_test_new/denxanh"
os.chdir(path)
os.listdir()
sort_listdir = sorted_alphanumeric(os.listdir())
sort_listdir

['vungtau_17.0.avi_save',
 'vungtau_18.0.avi_save',
 'vungtau_147.0.avi_save',
 'vungtau_152.0.avi_save',
 'vungtau_157.0.avi_save',
 'vungtau_163.0.avi_save',
 'vungtau_169.0.avi_save',
 'vungtau_174.0.avi_save',
 'vungtau_175.0.avi_save',
 'vungtau_181.0.avi_save',
 'vungtau_185.0.avi_save',
 'vungtau_186.0.avi_save',
 'vungtau_191.0.avi_save',
 'vungtau_196.0.avi_save']

In [19]:
id = []
sequence_id = []
labels = []
for i in data_vungtau_loc: #i la bo du lieu folder thu i
    for j in i:
      id.append(j[1])
    break
print(list(set(id)))

number_folder = 0
for i in data_vungtau_loc: #i la bo du lieu folder thu i
    #lấy ra tập chứa các id trong folder
    for j in i:
      id.append(j[1])
    for l in id: #duyet id tu tap id
      for k in data_vungtau[number_folder]: #duyet qua cac frame
        if k[1]==l: #neu id frame = id trong tap id
          sequence_id.append(k[:]) #lay ra thong tin sequence  
      #print(sequence_id)
      #ghi ra file sequence of id
      path = '/content/drive/MyDrive/Project/data_test_new/denxanh/' + sort_listdir[number_folder] + '/'
      ghifile(path, sequence_id)
      sequence_id = [] #khoi tao lai sequence_id = rong
    number_folder = number_folder + 1
    id = [] #khởi tạo lại id = rỗng

[70.0, 8.0, 9.0, 40.0, 79.0, 25.0, 62.0]


## Lọc data

In [6]:
def linear_equation(x1,y1,x2,y2):
    a = (y1-y2)/(x1-x2)
    c = y1-a*x1
    b = -1
    return a, b, c

In [7]:
def safe(value1, value2):
    if value1*value2>=0:
        return True
    return False

Lọc data ở Hà Nam (đèn xanh)

In [ ]:
# Các điểm cho trước trên vùng lọc
x1 = 2.9411764705882035
y1 = 1142.8823529411764
x2 = 935.2941176470588
y2 = 701.7058823529411
x3 = 1752.941176470588
y3 = 725.235294117647
x4 = 2400.0
y4 = 1916.4117647058822
# Điểm để xét trong vùng đang quan sát
X = 1280
Y = 1920

# Đường thẳng lọc data hà nam
a1, b1, c1 = linear_equation(x1,y1,x2,y2)
a2, b2, c2 = linear_equation(x2,y2,x3,y3)
a3, b3, c3 = linear_equation(x3,y3,x4,y4)

In [ ]:
filtered_data_hanam = []

for datas in data_hanam:
    filters = []
    for data in datas:
        if (safe(a1*X+b1*Y+c1, a1*((data[4]+data[3])/2)+b1*((data[6]+data[5])/2)+c1)==True 
        and safe(a2*X+b2*Y+c2, a2*((data[4]+data[3])/2)+b2*((data[6]+data[5])/2)+c2)==True
        and safe(a3*X+b3*Y+c3, a3*((data[4]+data[3])/2)+b3*((data[6]+data[5])/2)+c3)==True):
            filters.append(data)
    filtered_data_hanam.append(filters)

In [ ]:
len(filtered_data_hanam[0])

587

In [ ]:
len(data_hanam[0])

1244

Lọc data Vũng Tàu (đèn xanh)

In [8]:
# Các điểm cho trước trên vùng lọc
x8 = 0.0
y8 = 1130.0
x9 = 807.0
y9 = 606.0
x10 = 2361
y10 = 658
# Điểm để xét trong vùng đang quan sát
X = 807.0
Y = 1130.0

# Đường thẳng lọc data vũng tàu
a6, b6, c6 = linear_equation(x8,y8,x9,y9)
a7, b7, c7 = linear_equation(x9,y9,x10,y10)

In [9]:
filtered_data_vungtau = []

for datas in data_vungtau:
    filters = []
    for data in datas:
        if (safe(a6*X+b6*Y+c6, a6*((data[4]+data[3])/2)+b6*((data[6]+data[5])/2)+c6)==True 
        and safe(a7*X+b7*Y+c7, a7*((data[4]+data[3])/2)+b7*((data[6]+data[5])/2)+c7)==True):
            filters.append(data)
    filtered_data_vungtau.append(filters)

In [10]:
len(data_vungtau[7])

4682

In [11]:
len(filtered_data_vungtau[7])

475

## Ghi kết quả lọc được ra file

Ghi dữ liệu của Hà Nam và Vũng Tàu

Ghi ra Hà Nam

In [ ]:
path = '/content/drive/MyDrive/Project/data_test/filtered_denxanh_data/'

i=0
for datas in filtered_data_hanam:
  i = i + 1
  with open(path+str(i)+'.txt', 'w') as f:
    for data in datas:
      data = data.tolist()  # conver to Python list
      f.write(','.join(map(str, data)) + '\n')
  f.close()

Ghi dữ liệu Vũng Tàu

In [12]:
path = '/content/drive/MyDrive/Project/data_test_new/filtered_denxanh_data/'

i=0
for datas in filtered_data_vungtau:
  i = i + 1
  with open(path+str(i)+'.txt', 'w') as f:
    for data in datas:
      data = data.tolist()  # conver to Python list
      f.write(','.join(map(str, data)) + '\n')
  f.close()

Tiếp theo dùng lọc để lấy id xét xong quay lại file gốc lấy sequence của các id xuất hiện trong file lọc 